[package]
name = "appkit-nsworkspace-bindings"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true

[target.'cfg(target_os = "macos")'.build-dependencies]
bindgen = "0.71.1"

[target.'cfg(target_os = "macos")'.dependencies]
objc.workspace = true
