[package]
name = "accessibility-sys"
version = "0.1.3"
authors = ["Mack Straight <mack@discordapp.com>"]
edition = "2018"
license = "MIT / Apache-2.0"
homepage = "https://github.com/eiz/accessibility"
repository = "https://github.com/eiz/accessibility"
description = "Bindings for macOS Accessibility services"
publish = false

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation-sys = "0.8"
core-foundation = "0.9"
core-graphics = "0.23.0"

[package.metadata.docs.rs]
default-target = "x86_64-apple-darwin"
