name: Typescript

on:
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  run-test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install protobuf compiler and libglib2.0
        run: sudo apt-get update && sudo apt-get install -y -qq protobuf-compiler libglib2.0-dev-bin
      - name: Cache .turbo folder
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-test-${{ runner.os }}-${{ github.sha }}
          restore-keys: turbo-test-${{ runner.os }}-
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"
      - name: Install npm dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run test:ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        if: github.event.repository.fork == false
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          fail_ci_if_error: true

  run-lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install protobuf compiler
        run: sudo apt-get update && sudo apt-get install -y -qq protobuf-compiler
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"
      - name: Install npm dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm run lint

  audit:
    name: Audit
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
