name: Typos

on:
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  typos:
    name: Spell Check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@master
