[package]
name = "fig_desktop-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
fig_ipc.workspace = true
fig_util.workspace = true
tempfile.workspace = true
tokio.workspace = true
fig_proto = { workspace = true, features = ["arbitrary"] }

[[bin]]
name = "local_ipc"
path = "fuzz_targets/local_ipc.rs"
test = false
doc = false
